<?php
// Include header
include_once 'includes/header.php';
?>

<div class="jumbotron p-5 mb-4 bg-light rounded-3">
    <div class="container py-5">
        <h1 class="display-5 fw-bold">Carbon Footprint Calculator</h1>
        <p class="col-md-8 fs-4">Calculate and track your carbon emissions to understand your environmental impact and find ways to reduce it.</p>
        <?php if (!isLoggedIn()): ?>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a href="register.php" class="btn btn-primary btn-lg px-4 me-md-2">Register</a>
                <a href="login.php" class="btn btn-outline-secondary btn-lg px-4">Login</a>
            </div>
        <?php else: ?>
            <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                <a href="dashboard.php" class="btn btn-primary btn-lg px-4 me-md-2">Go to Dashboard</a>
            </div>
        <?php endif; ?>
    </div>
</div>

<div class="row align-items-md-stretch">
    <div class="col-md-4">
        <div class="h-100 p-5 text-white bg-primary rounded-3">
            <h2>Track Energy Usage</h2>
            <p>Monitor your electricity, natural gas, fuel oil, and propane consumption to understand your home energy emissions.</p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="h-100 p-5 bg-danger text-white rounded-3">
            <h2>Analyze Transportation</h2>
            <p>Calculate emissions from your daily commute, road trips, and other travel based on vehicle type and distance.</p>
        </div>
    </div>
    <div class="col-md-4">
        <div class="h-100 p-5 bg-warning text-dark rounded-3">
            <h2>Measure Waste Impact</h2>
            <p>Understand how your waste disposal habits contribute to your overall carbon footprint.</p>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3>Why Calculate Your Carbon Footprint?</h3>
            </div>
            <div class="card-body">
                <p>Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by your actions. Understanding your carbon footprint is the first step toward reducing your impact on climate change.</p>
                <p>This calculator uses IBM's GHG APIs to provide accurate estimates of your emissions based on your energy consumption, transportation habits, and waste generation.</p>
                <p>By tracking your carbon footprint over time, you can:</p>
                <ul>
                    <li>Identify the biggest contributors to your emissions</li>
                    <li>Set realistic goals for reduction</li>
                    <li>Measure your progress</li>
                    <li>Make informed choices about lifestyle changes</li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php
// Include footer
include_once 'includes/footer.php';
?> 